// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"ki-book/app/book/admin/internal/biz"
	"ki-book/app/book/admin/internal/conf"
	"ki-book/app/book/admin/internal/data"
	"ki-book/app/book/admin/internal/server"
	"ki-book/app/book/admin/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	discovery := biz.NewDiscovery(registry)
	userClient := biz.NewUserServiceClient(discovery)
	userUseCase := biz.NewUserCase(userRepo, logger, userClient)
	bookAdminService := service.NewBookAdminService(userUseCase)
	grpcServer := server.NewGRPCServer(confServer, logger, bookAdminService)
	registrar := server.NewRegistrar(registry)
	httpServer := server.NewHTTPServer(confServer, logger, bookAdminService)
	app := newApp(logger, grpcServer, registrar, httpServer)
	return app, func() {
	}, nil
}
